INHERIT: ./_base.yml

site_url: https://docs.mmesh.io/platform/
use_directory_urls: true

docs_dir: ../docs/platform
site_dir: ../site/platform

nav:
  - 🡠 Back: /
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quick start: getting-started/quickstart.md
    - Features: getting-started/features.md
    - Integrations: getting-started/integrations.md
  - Installation:
    - Overview: installation/overview.md
    - Command Line Tool: installation/cli.md
    - Nodes: installation/nodes.md
  - Concepts:
    - Overview: concepts/overview.md
    - Architecture: concepts/architecture.md
  - Networking:
    - Overview: networking/overview.md
    - Topology: networking/topology.md
    - Nodes: networking/nodes.md
    - Network Security: networking/network-security.md
    - Service Discovery: networking/service-discovery.md
    - Advanced Features: networking/advanced-features.md
    - Best Practices: networking/best-practices.md
  - Kubernetes:
    - Overview: kubernetes/overview.md
    - Services: kubernetes/services.md
    - Pods: kubernetes/pods.md
  - Automation (Ops):
    - Overview: automation/overview.md
    - Workflows: automation/workflows.md
    - Projects: automation/projects.md
  - Monitoring:
    - Overview: monitoring/overview.md
    - Analytics: monitoring/analytics.md
    - Alerts: monitoring/alerts.md
  - IAM:
    - Overview: iam/overview.md
    - Users: iam/users.md
    - Authentication: iam/authentication.md
    - Authorization: iam/authorization.md
  - Administration:
    - Tenants: administration/tenants.md
    - Networks: administration/networks.md
    - Subnets: administration/subnets.md
    - Nodes: administration/nodes.md
    - Kubernetes: administration/kubernetes.md
    - 'Ops: Projects': administration/ops-projects.md
    - 'Ops: Workflows': administration/ops-workflows.md
    - Alerts: administration/alerts.md
    - 'IAM: Users': administration/iam-users.md
    - 'IAM: Security Groups': administration/iam-security-groups.md
    - 'IAM: Roles': administration/iam-roles.md
    - 'IAM: ACLs': administration/iam-acls.md
    - User Settings: administration/user.md
    - Account Administration: administration/account.md
  - Reference:
    - 'Node Configuration Reference': reference/mmesh-node.yml.md
    - 'Command Line Tool Configuration Reference': reference/mmeshctl.yml.md
    - 'Workflow Configuration Reference': reference/workflow.yml.md
  - FAQ: faq.md
  - Tags: tags.md
